services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile # <- use your dev Dockerfile
    working_dir: /app # <- consistent working dir
    command: npm run dev # nest --watch + prisma --watch
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app:cached # mount WHOLE project at /app
      - /app/node_modules # keep container's node_modules
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: postgresprisma
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    depends_on:
      - postgres

volumes:
  postgres:
    name: nest-prisma-db
