services:
  lexibase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lexibase
    working_dir: /app
    command: sh -lc "npx prisma migrate deploy && npm run dev"
    ports: [ "3000:3000" ]
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app:cached
      - /app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgresprisma
    restart: always
    ports: [ "5432:5432" ]
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-prisma-db
